// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friend_requests (id, sender_id, recipient_id, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, sender_id, recipient_id, status, created_at, decided_at
`

type CreateFriendRequestParams struct {
	ID          uuid.UUID `json:"id"`
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, createFriendRequest, arg.ID, arg.SenderID, arg.RecipientID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friendships (id, user_id_a, user_id_b) VALUES ($1, $2, $3)
`

type CreateFriendshipParams struct {
	ID      uuid.UUID `json:"id"`
	UserIDA uuid.UUID `json:"user_id_a"`
	UserIDB uuid.UUID `json:"user_id_b"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.Exec(ctx, createFriendship, arg.ID, arg.UserIDA, arg.UserIDB)
	return err
}

const decideFriendRequest = `-- name: DecideFriendRequest :one
UPDATE friend_requests SET status = $2, decided_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, sender_id, recipient_id, status, created_at, decided_at
`

type DecideFriendRequestParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) DecideFriendRequest(ctx context.Context, arg DecideFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, decideFriendRequest, arg.ID, arg.Status)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const friendshipExists = `-- name: FriendshipExists :one
SELECT EXISTS (SELECT 1 FROM friendships WHERE user_id_a = $1 AND user_id_b = $2)
`

type FriendshipExistsParams struct {
	UserIDA uuid.UUID `json:"user_id_a"`
	UserIDB uuid.UUID `json:"user_id_b"`
}

func (q *Queries) FriendshipExists(ctx context.Context, arg FriendshipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, friendshipExists, arg.UserIDA, arg.UserIDB)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFriendRequest = `-- name: GetFriendRequest :one
SELECT id, sender_id, recipient_id, status, created_at, decided_at FROM friend_requests WHERE id = $1
`

func (q *Queries) GetFriendRequest(ctx context.Context, id uuid.UUID) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, getFriendRequest, id)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getPendingFriendRequest = `-- name: GetPendingFriendRequest :one
SELECT id, sender_id, recipient_id, status, created_at, decided_at FROM friend_requests
WHERE sender_id = $1 AND recipient_id = $2 AND status = 'pending'
`

type GetPendingFriendRequestParams struct {
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) GetPendingFriendRequest(ctx context.Context, arg GetPendingFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, getPendingFriendRequest, arg.SenderID, arg.RecipientID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const latestFriendRequestRejection = `-- name: LatestFriendRequestRejection :one
SELECT MAX(decided_at)::timestamptz AS decided_at FROM friend_requests
WHERE sender_id = $1 AND recipient_id = $2 AND status = 'rejected'
`

type LatestFriendRequestRejectionParams struct {
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) LatestFriendRequestRejection(ctx context.Context, arg LatestFriendRequestRejectionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestFriendRequestRejection, arg.SenderID, arg.RecipientID)
	var decided_at pgtype.Timestamptz
	err := row.Scan(&decided_at)
	return decided_at, err
}

const listFriends = `-- name: ListFriends :many
SELECT f.user_id_b AS friend_id FROM friendships AS f WHERE f.user_id_a = $1
UNION
SELECT f.user_id_a AS friend_id FROM friendships AS f WHERE f.user_id_b = $1
`

func (q *Queries) ListFriends(ctx context.Context, userIDA uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFriends, userIDA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var friend_id uuid.UUID
		if err := rows.Scan(&friend_id); err != nil {
			return nil, err
		}
		items = append(items, friend_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
