// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const leaderboardPersonalBest = `-- name: LeaderboardPersonalBest :many
SELECT rp.user_id, MIN(rp.elapsed_milliseconds)::integer AS elapsed_milliseconds
FROM race_participants AS rp
JOIN races AS r ON r.id = rp.race_id
WHERE r.race_type_id = $1
  AND rp.status = 'finished'
  AND ($2::timestamptz IS NULL OR rp.finished_at >= $2)
  AND ($3::uuid[] IS NULL OR rp.user_id = ANY($3))
GROUP BY rp.user_id
ORDER BY elapsed_milliseconds ASC, rp.user_id ASC
`

type LeaderboardPersonalBestParams struct {
	RaceTypeID uuid.UUID          `json:"race_type_id"`
	Column2    pgtype.Timestamptz `json:"column_2"`
	Column3    []uuid.UUID        `json:"column_3"`
}

type LeaderboardPersonalBestRow struct {
	UserID              uuid.UUID `json:"user_id"`
	ElapsedMilliseconds int32     `json:"elapsed_milliseconds"`
}

func (q *Queries) LeaderboardPersonalBest(ctx context.Context, arg LeaderboardPersonalBestParams) ([]LeaderboardPersonalBestRow, error) {
	rows, err := q.db.Query(ctx, leaderboardPersonalBest, arg.RaceTypeID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardPersonalBestRow{}
	for rows.Next() {
		var i LeaderboardPersonalBestRow
		if err := rows.Scan(&i.UserID, &i.ElapsedMilliseconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
