// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BeginRaceRoom(ctx context.Context, id uuid.UUID) (Room, error)
	CountRecentPasswordResetsByEmail(ctx context.Context, email string) (int64, error)
	CountRecentVerificationCodesByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequest, error)
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error
	CreateRace(ctx context.Context, arg CreateRaceParams) (Race, error)
	CreateRaceParticipant(ctx context.Context, arg CreateRaceParticipantParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecideFriendRequest(ctx context.Context, arg DecideFriendRequestParams) (FriendRequest, error)
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeleteStalePasswordResetTokens(ctx context.Context) (int64, error)
	DeleteStaleVerificationCodes(ctx context.Context) (int64, error)
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	FinishRace(ctx context.Context, arg FinishRaceParams) error
	FinishRaceParticipant(ctx context.Context, arg FinishRaceParticipantParams) error
	FriendshipExists(ctx context.Context, arg FriendshipExistsParams) (bool, error)
	GetFriendRequest(ctx context.Context, id uuid.UUID) (FriendRequest, error)
	GetOldestRecentVerificationCode(ctx context.Context, userID uuid.UUID) (pgtype.Timestamptz, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetPendingFriendRequest(ctx context.Context, arg GetPendingFriendRequestParams) (FriendRequest, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVerificationCodeByTokenHash(ctx context.Context, tokenHash string) (EmailVerificationCode, error)
	IncrementFailedLoginAttempts(ctx context.Context, id uuid.UUID) error
	InsertEmailVerificationCode(ctx context.Context, arg InsertEmailVerificationCodeParams) (EmailVerificationCode, error)
	InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (PasswordResetToken, error)
	InsertRaceTelemetry(ctx context.Context, arg InsertRaceTelemetryParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	LatestFriendRequestRejection(ctx context.Context, arg LatestFriendRequestRejectionParams) (pgtype.Timestamptz, error)
	ListActiveRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	ListFriends(ctx context.Context, userIDA uuid.UUID) ([]uuid.UUID, error)
	ListRaceRoomParticipants(ctx context.Context, roomID uuid.UUID) ([]uuid.UUID, error)
	ListRaceStandings(ctx context.Context, arg ListRaceStandingsParams) ([]ListRaceStandingsRow, error)
	LockAccount(ctx context.Context, arg LockAccountParams) error
	LockRace(ctx context.Context, id uuid.UUID) (LockRaceRow, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error
	MarkRaceParticipantDNF(ctx context.Context, id uuid.UUID) error
	MarkVerificationCodeUsed(ctx context.Context, id uuid.UUID) error
	ResetLoginAttempts(ctx context.Context, id uuid.UUID) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdateRefreshTokenLastUsed(ctx context.Context, arg UpdateRefreshTokenLastUsedParams) error
}

var _ Querier = (*Queries)(nil)
