// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quick_match.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueQuickMatch = `-- name: EnqueueQuickMatch :exec
INSERT INTO quick_match_queue (id, user_id, race_type_id)
VALUES ($1, $2, $3)
`

type EnqueueQuickMatchParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	RaceTypeID uuid.UUID `json:"race_type_id"`
}

func (q *Queries) EnqueueQuickMatch(ctx context.Context, arg EnqueueQuickMatchParams) error {
	_, err := q.db.Exec(ctx, enqueueQuickMatch, arg.ID, arg.UserID, arg.RaceTypeID)
	return err
}

const leaveQuickMatch = `-- name: LeaveQuickMatch :exec
DELETE FROM quick_match_queue WHERE user_id = $1 AND race_type_id = $2
`

type LeaveQuickMatchParams struct {
	UserID     uuid.UUID `json:"user_id"`
	RaceTypeID uuid.UUID `json:"race_type_id"`
}

func (q *Queries) LeaveQuickMatch(ctx context.Context, arg LeaveQuickMatchParams) error {
	_, err := q.db.Exec(ctx, leaveQuickMatch, arg.UserID, arg.RaceTypeID)
	return err
}

const listWaitingByRaceType = `-- name: ListWaitingByRaceType :many
SELECT user_id, joined_at,
       EXTRACT(EPOCH FROM (NOW() - joined_at))::double precision AS waited_seconds
FROM quick_match_queue
WHERE race_type_id = $1
ORDER BY joined_at ASC, id ASC
FOR UPDATE
`

type ListWaitingByRaceTypeRow struct {
	UserID        uuid.UUID          `json:"user_id"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
	WaitedSeconds float64            `json:"waited_seconds"`
}

func (q *Queries) ListWaitingByRaceType(ctx context.Context, raceTypeID uuid.UUID) ([]ListWaitingByRaceTypeRow, error) {
	rows, err := q.db.Query(ctx, listWaitingByRaceType, raceTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaitingByRaceTypeRow{}
	for rows.Next() {
		var i ListWaitingByRaceTypeRow
		if err := rows.Scan(&i.UserID, &i.JoinedAt, &i.WaitedSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentFinishesByRaceType = `-- name: RecentFinishesByRaceType :many
SELECT rp.elapsed_milliseconds, rp.finished_at
FROM race_participants AS rp
JOIN races AS r ON r.id = rp.race_id
WHERE r.race_type_id = $1 AND rp.user_id = $2
  AND rp.status = 'finished'
ORDER BY rp.finished_at DESC NULLS LAST, rp.id DESC
`

type RecentFinishesByRaceTypeParams struct {
	RaceTypeID uuid.UUID `json:"race_type_id"`
	UserID     uuid.UUID `json:"user_id"`
}

type RecentFinishesByRaceTypeRow struct {
	ElapsedMilliseconds pgtype.Int4        `json:"elapsed_milliseconds"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) RecentFinishesByRaceType(ctx context.Context, arg RecentFinishesByRaceTypeParams) ([]RecentFinishesByRaceTypeRow, error) {
	rows, err := q.db.Query(ctx, recentFinishesByRaceType, arg.RaceTypeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentFinishesByRaceTypeRow{}
	for rows.Next() {
		var i RecentFinishesByRaceTypeRow
		if err := rows.Scan(&i.ElapsedMilliseconds, &i.FinishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
