// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: races.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginRaceRoom = `-- name: BeginRaceRoom :one
UPDATE rooms SET status = 'in_progress'
WHERE id = $1 AND status = 'counting_down'
RETURNING id, race_type_id, host_user_id, status, join_code, created_at
`

func (q *Queries) BeginRaceRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, beginRaceRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RaceTypeID,
		&i.HostUserID,
		&i.Status,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const createRace = `-- name: CreateRace :one
INSERT INTO races (id, room_id, race_type_id, started_at)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, race_type_id, started_at, finished_at
`

type CreateRaceParams struct {
	ID         uuid.UUID          `json:"id"`
	RoomID     uuid.UUID          `json:"room_id"`
	RaceTypeID uuid.UUID          `json:"race_type_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateRace(ctx context.Context, arg CreateRaceParams) (Race, error) {
	row := q.db.QueryRow(ctx, createRace,
		arg.ID,
		arg.RoomID,
		arg.RaceTypeID,
		arg.StartedAt,
	)
	var i Race
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RaceTypeID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createRaceParticipant = `-- name: CreateRaceParticipant :exec
INSERT INTO race_participants (id, race_id, user_id, status)
VALUES ($1, $2, $3, 'racing')
`

type CreateRaceParticipantParams struct {
	ID     uuid.UUID `json:"id"`
	RaceID uuid.UUID `json:"race_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateRaceParticipant(ctx context.Context, arg CreateRaceParticipantParams) error {
	_, err := q.db.Exec(ctx, createRaceParticipant, arg.ID, arg.RaceID, arg.UserID)
	return err
}

const finishRace = `-- name: FinishRace :exec
UPDATE races SET finished_at = $2 WHERE id = $1 AND finished_at IS NULL
`

type FinishRaceParams struct {
	ID         uuid.UUID          `json:"id"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) FinishRace(ctx context.Context, arg FinishRaceParams) error {
	_, err := q.db.Exec(ctx, finishRace, arg.ID, arg.FinishedAt)
	return err
}

const finishRaceParticipant = `-- name: FinishRaceParticipant :exec
UPDATE race_participants
SET status = 'finished', elapsed_milliseconds = $2, finished_at = $3
WHERE id = $1 AND status <> 'dnf'
`

type FinishRaceParticipantParams struct {
	ID                  uuid.UUID          `json:"id"`
	ElapsedMilliseconds pgtype.Int4        `json:"elapsed_milliseconds"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) FinishRaceParticipant(ctx context.Context, arg FinishRaceParticipantParams) error {
	_, err := q.db.Exec(ctx, finishRaceParticipant, arg.ID, arg.ElapsedMilliseconds, arg.FinishedAt)
	return err
}

const insertRaceTelemetry = `-- name: InsertRaceTelemetry :exec
INSERT INTO telemetry_samples
(id, race_id, user_id, elapsed_milliseconds, distance_millimeters, stroke_rate, power, sampled_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRaceTelemetryParams struct {
	ID                  uuid.UUID          `json:"id"`
	RaceID              uuid.UUID          `json:"race_id"`
	UserID              uuid.UUID          `json:"user_id"`
	ElapsedMilliseconds pgtype.Int8        `json:"elapsed_milliseconds"`
	DistanceMillimeters pgtype.Int8        `json:"distance_millimeters"`
	StrokeRate          pgtype.Int4        `json:"stroke_rate"`
	Power               pgtype.Int4        `json:"power"`
	SampledAt           pgtype.Timestamptz `json:"sampled_at"`
}

func (q *Queries) InsertRaceTelemetry(ctx context.Context, arg InsertRaceTelemetryParams) error {
	_, err := q.db.Exec(ctx, insertRaceTelemetry,
		arg.ID,
		arg.RaceID,
		arg.UserID,
		arg.ElapsedMilliseconds,
		arg.DistanceMillimeters,
		arg.StrokeRate,
		arg.Power,
		arg.SampledAt,
	)
	return err
}

const listRaceRoomParticipants = `-- name: ListRaceRoomParticipants :many
SELECT user_id FROM room_participants WHERE room_id = $1 ORDER BY id
`

func (q *Queries) ListRaceRoomParticipants(ctx context.Context, roomID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRaceRoomParticipants, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaceStandings = `-- name: ListRaceStandings :many
SELECT p.id, p.user_id, p.status,
       latest.distance_millimeters, latest.elapsed_milliseconds, latest.sampled_at,
       target.elapsed_milliseconds AS target_elapsed_milliseconds,
       target.sampled_at AS target_sampled_at
FROM race_participants p
LEFT JOIN LATERAL (
    SELECT s.distance_millimeters, s.elapsed_milliseconds, s.sampled_at
    FROM telemetry_samples s WHERE s.race_id = p.race_id AND s.user_id = p.user_id
    ORDER BY s.sampled_at DESC, s.id DESC LIMIT 1
) latest ON true
LEFT JOIN LATERAL (
    SELECT s.elapsed_milliseconds, s.sampled_at
    FROM telemetry_samples s
    WHERE s.race_id = p.race_id AND s.user_id = p.user_id
      AND s.distance_millimeters >= $2 AND s.elapsed_milliseconds IS NOT NULL
    ORDER BY s.elapsed_milliseconds ASC, s.sampled_at ASC, s.id ASC LIMIT 1
) target ON true
WHERE p.race_id = $1 ORDER BY p.id
`

type ListRaceStandingsParams struct {
	RaceID              uuid.UUID   `json:"race_id"`
	DistanceMillimeters pgtype.Int8 `json:"distance_millimeters"`
}

type ListRaceStandingsRow struct {
	ID                        uuid.UUID          `json:"id"`
	UserID                    uuid.UUID          `json:"user_id"`
	Status                    string             `json:"status"`
	DistanceMillimeters       pgtype.Int8        `json:"distance_millimeters"`
	ElapsedMilliseconds       pgtype.Int8        `json:"elapsed_milliseconds"`
	SampledAt                 pgtype.Timestamptz `json:"sampled_at"`
	TargetElapsedMilliseconds pgtype.Int8        `json:"target_elapsed_milliseconds"`
	TargetSampledAt           pgtype.Timestamptz `json:"target_sampled_at"`
}

func (q *Queries) ListRaceStandings(ctx context.Context, arg ListRaceStandingsParams) ([]ListRaceStandingsRow, error) {
	rows, err := q.db.Query(ctx, listRaceStandings, arg.RaceID, arg.DistanceMillimeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRaceStandingsRow{}
	for rows.Next() {
		var i ListRaceStandingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.DistanceMillimeters,
			&i.ElapsedMilliseconds,
			&i.SampledAt,
			&i.TargetElapsedMilliseconds,
			&i.TargetSampledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRace = `-- name: LockRace :one
SELECT r.id, r.room_id, r.race_type_id, r.started_at, r.finished_at, rt.kind, rt.target_value
FROM races r JOIN race_types rt ON rt.id = r.race_type_id
WHERE r.id = $1 FOR UPDATE OF r
`

type LockRaceRow struct {
	ID          uuid.UUID          `json:"id"`
	RoomID      uuid.UUID          `json:"room_id"`
	RaceTypeID  uuid.UUID          `json:"race_type_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	Kind        string             `json:"kind"`
	TargetValue int64              `json:"target_value"`
}

func (q *Queries) LockRace(ctx context.Context, id uuid.UUID) (LockRaceRow, error) {
	row := q.db.QueryRow(ctx, lockRace, id)
	var i LockRaceRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RaceTypeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.TargetValue,
	)
	return i, err
}

const markRaceParticipantDNF = `-- name: MarkRaceParticipantDNF :exec
UPDATE race_participants SET status = 'dnf' WHERE id = $1 AND status = 'racing'
`

func (q *Queries) MarkRaceParticipantDNF(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRaceParticipantDNF, id)
	return err
}
