// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const beginRoomRace = `-- name: BeginRoomRace :exec
UPDATE rooms SET status = 'in_progress' WHERE id = $1
`

func (q *Queries) BeginRoomRace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, beginRoomRace, id)
	return err
}

const countRoomParticipants = `-- name: CountRoomParticipants :one
SELECT count(*) FROM room_participants WHERE room_id = $1
`

func (q *Queries) CountRoomParticipants(ctx context.Context, roomID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomParticipants, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRoomParticipant = `-- name: DeleteRoomParticipant :exec
DELETE FROM room_participants WHERE room_id = $1 AND user_id = $2
`

type DeleteRoomParticipantParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRoomParticipant(ctx context.Context, arg DeleteRoomParticipantParams) error {
	_, err := q.db.Exec(ctx, deleteRoomParticipant, arg.RoomID, arg.UserID)
	return err
}

const dissolveRoom = `-- name: DissolveRoom :exec
UPDATE rooms SET status = 'dissolved' WHERE id = $1
`

func (q *Queries) DissolveRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, dissolveRoom, id)
	return err
}

const getActiveRoomByJoinCode = `-- name: GetActiveRoomByJoinCode :one
SELECT id, race_type_id, host_user_id, status, join_code, created_at FROM rooms
WHERE join_code = $1 AND status NOT IN ('finished', 'dissolved')
FOR UPDATE
`

func (q *Queries) GetActiveRoomByJoinCode(ctx context.Context, joinCode string) (Room, error) {
	row := q.db.QueryRow(ctx, getActiveRoomByJoinCode, joinCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RaceTypeID,
		&i.HostUserID,
		&i.Status,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const getRaceType = `-- name: GetRaceType :one
SELECT id, kind, target_value, label FROM race_types WHERE id = $1
`

func (q *Queries) GetRaceType(ctx context.Context, id uuid.UUID) (RaceType, error) {
	row := q.db.QueryRow(ctx, getRaceType, id)
	var i RaceType
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetValue,
		&i.Label,
	)
	return i, err
}

const getRemainingRoomParticipant = `-- name: GetRemainingRoomParticipant :one
SELECT user_id FROM room_participants WHERE room_id = $1 ORDER BY joined_at, id LIMIT 1
`

func (q *Queries) GetRemainingRoomParticipant(ctx context.Context, roomID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRemainingRoomParticipant, roomID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getRoomForUpdate = `-- name: GetRoomForUpdate :one
SELECT id, race_type_id, host_user_id, status, join_code, created_at FROM rooms WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRoomForUpdate(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomForUpdate, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RaceTypeID,
		&i.HostUserID,
		&i.Status,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomParticipant = `-- name: GetRoomParticipant :one
SELECT id, room_id, user_id, ready, joined_at FROM room_participants WHERE room_id = $1 AND user_id = $2 LIMIT 1
`

type GetRoomParticipantParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRoomParticipant(ctx context.Context, arg GetRoomParticipantParams) (RoomParticipant, error) {
	row := q.db.QueryRow(ctx, getRoomParticipant, arg.RoomID, arg.UserID)
	var i RoomParticipant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Ready,
		&i.JoinedAt,
	)
	return i, err
}

const insertRoom = `-- name: InsertRoom :exec
INSERT INTO rooms (id, race_type_id, host_user_id, status, join_code)
VALUES ($1, $2, $3, 'waiting', $4)
`

type InsertRoomParams struct {
	ID         uuid.UUID `json:"id"`
	RaceTypeID uuid.UUID `json:"race_type_id"`
	HostUserID uuid.UUID `json:"host_user_id"`
	JoinCode   string    `json:"join_code"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) error {
	_, err := q.db.Exec(ctx, insertRoom,
		arg.ID,
		arg.RaceTypeID,
		arg.HostUserID,
		arg.JoinCode,
	)
	return err
}

const insertRoomParticipant = `-- name: InsertRoomParticipant :exec
INSERT INTO room_participants (id, room_id, user_id, ready)
VALUES ($1, $2, $3, false)
`

type InsertRoomParticipantParams struct {
	ID     uuid.UUID `json:"id"`
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) InsertRoomParticipant(ctx context.Context, arg InsertRoomParticipantParams) error {
	_, err := q.db.Exec(ctx, insertRoomParticipant, arg.ID, arg.RoomID, arg.UserID)
	return err
}

const markRoomParticipantReady = `-- name: MarkRoomParticipantReady :exec
UPDATE room_participants SET ready = true WHERE room_id = $1 AND user_id = $2
`

type MarkRoomParticipantReadyParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkRoomParticipantReady(ctx context.Context, arg MarkRoomParticipantReadyParams) error {
	_, err := q.db.Exec(ctx, markRoomParticipantReady, arg.RoomID, arg.UserID)
	return err
}

const reassignRoomHost = `-- name: ReassignRoomHost :exec
UPDATE rooms SET host_user_id = $2 WHERE id = $1
`

type ReassignRoomHostParams struct {
	ID         uuid.UUID `json:"id"`
	HostUserID uuid.UUID `json:"host_user_id"`
}

func (q *Queries) ReassignRoomHost(ctx context.Context, arg ReassignRoomHostParams) error {
	_, err := q.db.Exec(ctx, reassignRoomHost, arg.ID, arg.HostUserID)
	return err
}

const roomHasUnreadyParticipants = `-- name: RoomHasUnreadyParticipants :one
SELECT EXISTS (SELECT 1 FROM room_participants WHERE room_id = $1 AND NOT ready)
`

func (q *Queries) RoomHasUnreadyParticipants(ctx context.Context, roomID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, roomHasUnreadyParticipants, roomID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const roomParticipantExists = `-- name: RoomParticipantExists :one
SELECT EXISTS (SELECT 1 FROM room_participants WHERE room_id = $1 AND user_id = $2)
`

type RoomParticipantExistsParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RoomParticipantExists(ctx context.Context, arg RoomParticipantExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, roomParticipantExists, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const startRoomCountdown = `-- name: StartRoomCountdown :exec
UPDATE rooms SET status = 'counting_down' WHERE id = $1
`

func (q *Queries) StartRoomCountdown(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startRoomCountdown, id)
	return err
}
